---
title: "Benjamin Horner"
output: 
  html_document:
    toc: true  # Add table of contents
    toc_float: true  # Float table of contents on the right side
---

<style>
body {
  font-family: Arial, sans-serif;
  background-color: #f5f5f5;
}

.container {
  display: flex;
}

.sidebar {
  flex: 0 0 20%;
  background-color: #333;
  color: #fff;
  padding: 20px;
}

.sidebar h2 {
  color: #ff9966;
}

.sidebar ul {
  list-style-type: none;
  padding: 0;
}

.sidebar li {
  margin-bottom: 10px;
}

.main-content {
  flex: 1;
  padding: 20px;
}

h2 {
  color: #ff9966;
}

.tableau-container {
  margin-top: 20px;
}
</style>

# My Portfolio

Welcome to my portfolio website! Here, you'll find information about my education, work experience, and projects.

## Education {#education}

### Master of Science in Business Analytics
- **University:** University of Tennessee
- **Year:** 2024-2025

### Bachelor of Science in Business Administration 
- **Major** Business Analytics
- **University:** University of Tennessee
- **Year:** 2020-2023

## Work Experience {#work-experience}


### Data Analytics Intern 
- **Company:** Clayton Homes
- **Duration:** May 2023 - August 2023
- **Description:** 
  - Conducted statistical analyses on market share data to identify key trends and insights. 
  - Created visualizations in Tableau to display actionable insights found in data. 
  - Queried data from Microsoft SQL Server to pull data for analysis. 
  - Communicated findings and analyses to executives.


### Software Engineer Intern
- **Company:** Internship Company
- **Duration:** Summer 20XX
- **Description:** Brief description of your internship experience.

## Projects {#projects}

### Project 1: Predictive Analytics
- **Description:** Brief description of the project and its goals.
- **Tools:** R, Python, etc.
- **Link:** [Project 1](#)

### Project 2: Data Visualization
- **Description:** Brief description of the project and its goals.
- **Tools:** Tableau, ggplot2, etc.
- **Link:** [Project 2](#)

### Project 3: Machine Learning
- **Description:** Brief description of the project and its goals.
- **Tools:** Scikit-learn, TensorFlow, etc.
- **Link:** 
```{r, echo=FALSE}
knitr::include_url("https://public.tableau.com/views/Carbs_16966302775830/Dashboard1?:showVizHome=no&:embed=true")
```

